#### Si se trabaja en entorno de google colab:

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [17]:
from IPython.display import display, HTML

# Ajuste de estilo para salida sin límite de ancho y largo
display(HTML("""
<style>
.output_scroll {
    height: auto;
    max-height: none;
    overflow-y: auto;
    white-space: pre;
    overflow-x: scroll;
}
</style>
"""))

#### Si se trabaja en local

In [28]:
import numpy as np
import pandas as pd
import os
import chardet

os.chdir('/content/drive/MyDrive/NoCountry_RiesgoCrediticio/recursos_y_notebooks') # en el caso de que se trabaje en google colab
%load_ext autoreload
%autoreload 2

import resources as r

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [20]:
# Este codigo Pone un limite grande para el ancho y sin limite para el largo de un output
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 1000)
pd.set_option('display.width', 1000)

In [29]:
lista_produccion = os.listdir('../raw/')
lista_produccion.pop(7)
lista_produccion

['produccin-de-pozos-de-gas-y-petrleo-no-convencional.csv',
 'capitulo-iv-pozos.csv',
 'produccin-de-pozos-de-gas-y-petrleo-2020.csv',
 'produccin-de-pozos-de-gas-y-petrleo-2021.csv',
 'produccin-de-pozos-de-gas-y-petrleo-2022.csv',
 'produccin-de-pozos-de-gas-y-petrleo-2023.csv',
 'produccin-de-pozos-de-gas-y-petrleo-2024.csv',
 'Precios petroleo mundia desde 1970.csv',
 'Petrol Price Worldwide.csv',
 'Produccion petroleras ARG 2009 - 2018.csv',
 'YPF NASDAQ.csv']

In [ ]:
# encontramos que existe un problema de encoding en algunos ficheros
# para explorarlos a fines practicos para el analisis preliminar, trataremos las excepciones buscando el encoding que se adecúe

In [31]:
for df in lista_produccion:
    with open(f'../raw/{df}', 'rb') as f: # abrimos el fuchero y lo leemos como dato binario
      result = chardet.detect(f.read()) # identificamos el tipo de encoding en que estan los datos
      encoding = result['encoding'] # obtenemos el valor de encoding que nos interesa y lo instanciamos a una variable
    data = pd.read_csv(f'../raw/{df}', encoding= encoding)
    informe = r.informe_dataframe(data)
    print(informe)

INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 303393
Columnas: 40

--Numero de datos--
11547859

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 303392
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'coordenadax', 'coordenaday', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
coordenadax               float64
coordenaday               float64
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 83990
Columnas: 26

--Numero de datos--
2038459

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 83989
Columnas: ['sigla', 'idpozo', 'area', 'cod_area', 'empresa', 'yacimiento', 'cod_yacimiento', 'formacion', 'cuenca', 'provincia', 'cota', 'profundidad', 'clasificacion', 'subclasificacion', 'tipo_recurso', 'sub_tipo_recurso', 'gasplus', 'tipopozo', 'tipoextraccion', 'tipoestado', 'adjiv_fecha_inicio_perf', 'adjiv_fecha_fin_perf', 'adjiv_fecha_inicio_term', 'adjiv_fecha_fin_term', 'geojson', 'geom']

--Tipo de columnas--
sigla                       object
idpozo                       int64
area                        object
cod_area                    object
empresa                     object
yacimiento                  object
cod_yacimiento              object
formacion                   object
cuenca                      object
provincia                   object
cota                       float64
profundidad                float64
clasificacion               object
subclasificacion            object
tipo_recurso                object
sub_tipo_recurso            object
gasplus                     object
tipopozo                    object
tipoextraccion              object
tipoestado                  object
adjiv_fecha_inicio_perf     object
adjiv_fecha_fin_perf        object
adjiv_fecha_inicio_term     object
adjiv_fecha_fin_term        object
geojson                     object
geom                        object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 953660
Columnas: 38

--Numero de datos--
33036239

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 953659
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 961451
Columnas: 38

--Numero de datos--
33300601

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 961450
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 972353
Columnas: 38

--Numero de datos--
33669674

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 972352
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 974958
Columnas: 38

--Numero de datos--
33785463

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 974957
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 409352
Columnas: 38

--Numero de datos--
14189243

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 409351
Columnas: ['idempresa', 'anio', 'mes', 'idpozo', 'prod_pet', 'prod_gas', 'prod_agua', 'iny_agua', 'iny_gas', 'iny_co2', 'iny_otro', 'tef', 'vida_util', 'tipoextraccion', 'tipoestado', 'tipopozo', 'observaciones', 'fechaingreso', 'rectificado', 'habilitado', 'idusuario', 'empresa', 'sigla', 'formprod', 'profundidad', 'formacion', 'idareapermisoconcesion', 'areapermisoconcesion', 'idareayacimiento', 'areayacimiento', 'cuenca', 'provincia', 'tipo_de_recurso', 'proyecto', 'clasificacion', 'subclasificacion', 'sub_tipo_recurso', 'fecha_data']

--Tipo de columnas--
idempresa                  object
anio                        int64
mes                         int64
idpozo                      int64
prod_pet                  float64
prod_gas                  float64
prod_agua                 float64
iny_agua                  float64
iny_gas                   float64
iny_co2                   float64
iny_otro                  float64
tef                       float64
vida_util                 float64
tipoextraccion             object
tipoestado                 object
tipopozo                   object
observaciones              object
fechaingreso               object
rectificado                object
habilitado                 object
idusuario                   int64
empresa                    object
sigla                      object
formprod                   object
profundidad               float64
formacion                  object
idareapermisoconcesion     object
areapermisoconcesion       object
idareayacimiento           object
areayacimiento             object
cuenca                     object
provincia                  object
tipo_de_recurso            object
proyecto                   object
clasificacion              object
subclasificacion           object
sub_tipo_recurso           object
fecha_data                 object
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 264
Columnas: 60

--Numero de datos--
11762

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 263
Columnas: ['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', '1966', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022', '2023', 'Unnamed: 68']

--Tipo de columnas--
Country Name       object
Country Code       object
Indicator Name     object
Indicator Code     object
1966              float64
1970              float64
1971              float64
1972              float64
1973              float64
1974              float64
1975              float64
1976              float64
1977              float64
1978              float64
1979              float64
1980              float64
1981              float64
1982              float64
1983              float64
1984              float64
1985              float64
1986              float64
1987              float64
1988              float64
1989              float64
1990              float64
1991              float64
1992              float64
1993              float64
1994              float64
1995              float64
1996              float64
1997              float64
1998              float64
1999              float64
2000              float64
2001              float64
2002              float64
2003              float64
2004              float64
2005              float64
2006              float64
2007              float64
2008              float64
2009              float64
2010              float64
2011              float64
2012              float64
2013              float64
2014              float64
2015              float64
2016              float64
2017              float64
2018              float64
2019              float64
2020              float64
2021              float64
2022              float64
2023              float64
Unnamed: 68       float64
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 181
Columnas: 11

--Numero de datos--
1991

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 180
Columnas: ['S#', 'Country', 'Daily Oil Consumption (Barrels)', 'World Share', 'Yearly Gallons Per Capita', 'Price Per Gallon (USD)', 'Price Per Liter (USD)', 'Price Per Liter (PKR)', 'GDP Per Capita ( USD )', 'Gallons GDP Per Capita Can Buy', 'xTimes Yearly Gallons Per Capita Buy']

--Tipo de columnas--
S#                                        int64
Country                                  object
Daily Oil Consumption (Barrels)          object
World Share                              object
Yearly Gallons Per Capita               float64
Price Per Gallon (USD)                  float64
Price Per Liter (USD)                   float64
Price Per Liter (PKR)                   float64
GDP Per Capita ( USD )                   object
Gallons GDP Per Capita Can Buy           object
xTimes Yearly Gallons Per Capita Buy      int64
dtype: object
--Cantidad de registros duplicados--
0

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~oo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
INFORME PRELIMINAR SOBRE CARACTERISTICAS DEL DATASET:

--Dimensiones del DataFrame--
Filas: 1187
Columnas: 14

--Numero de datos--
827

--Filas y Columnas--
Filas: muestra de indices-------> [0, 1, 2, 3, 4]  -----> Desde 0  Hasta 1186
Columnas: ['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13']

--Tipo de columnas--
Unnamed: 0     object
Unnamed: 1     object
Unnamed: 2     object
Unnamed: 3     object
Unnamed: 4     object
Unnamed: 5     object
Unnamed: 6     object
Unnamed: 7     object
Unnamed: 8     object
Unnamed: 9     object
Unnamed: 10    object
Unnamed: 11    object
Unnamed: 12    object
Unnamed: 13    object
dtype: object
--Cantidad de registros duplicados--
1117


In [34]:
for df in lista_produccion:
    with open(f'../raw/{df}', 'rb') as f: # abrimos el fuchero y lo leemos como dato binario
      result = chardet.detect(f.read()) # identificamos el tipo de encoding en que estan los datos
      encoding = result['encoding'] # obtenemos el valor de encoding que nos interesa y lo instanciamos a una variable
    data = pd.read_csv(f'../raw/{df}', encoding= encoding)
    print(f'Nombre de fichero: {df}      encoding= {str(encoding)}\n')
    print(r.verificar_tipo_datos(data))
    print('-'*80)
    print()

Nombre de fichero: produccin-de-pozos-de-gas-y-petrleo-no-convencional.csv      encoding= UTF-8-SIG

              nombre_campo                        tipo_datos  no_nulos_%  nulos_%   nulos
0                idempresa                   [<class 'str'>]      100.00     0.00       0
1                     anio                   [<class 'int'>]      100.00     0.00       0
2                      mes                   [<class 'int'>]      100.00     0.00       0
3                   idpozo                   [<class 'int'>]      100.00     0.00       0
4                 prod_pet                 [<class 'float'>]      100.00     0.00       0
5                 prod_gas                 [<class 'float'>]      100.00     0.00       0
6                prod_agua                 [<class 'float'>]      100.00     0.00       0
7                 iny_agua                 [<class 'float'>]      100.00     0.00       0
8                  iny_gas                 [<class 'float'>]      100.00     0.00       0
9                  iny_co2                 [<class 'float'>]      100.00     0.00       0
10                iny_otro                 [<class 'float'>]      100.00     0.00       0
11                     tef                 [<class 'float'>]      100.00     0.00       0
12               vida_util                 [<class 'float'>]        2.03    97.97  297223
13          tipoextraccion  [<class 'str'>, <class 'float'>]       99.81     0.19     563
14              tipoestado  [<class 'str'>, <class 'float'>]       99.81     0.19     563
15                tipopozo  [<class 'str'>, <class 'float'>]       99.81     0.19     563
16           observaciones  [<class 'float'>, <class 'str'>]        5.41    94.59  286965
17            fechaingreso                   [<class 'str'>]      100.00     0.00       0
18             rectificado                   [<class 'str'>]      100.00     0.00       0
19              habilitado                   [<class 'str'>]      100.00     0.00       0
20               idusuario                   [<class 'int'>]      100.00     0.00       0
21                 empresa                   [<class 'str'>]      100.00     0.00       0
22                   sigla                   [<class 'str'>]      100.00     0.00       0
23                formprod                   [<class 'str'>]      100.00     0.00       0
24             profundidad                 [<class 'float'>]      100.00     0.00       0
25               formacion                   [<class 'str'>]      100.00     0.00       0
26  idareapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
27    areapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
28        idareayacimiento                   [<class 'str'>]      100.00     0.00       0
29          areayacimiento                   [<class 'str'>]      100.00     0.00       0
30                  cuenca                   [<class 'str'>]      100.00     0.00       0
31               provincia                   [<class 'str'>]      100.00     0.00       0
32             coordenadax                 [<class 'float'>]      100.00     0.00       0
33             coordenaday                 [<class 'float'>]      100.00     0.00       0
34         tipo_de_recurso                   [<class 'str'>]      100.00     0.00       0
35                proyecto                   [<class 'str'>]      100.00     0.00       0
36           clasificacion  [<class 'str'>, <class 'float'>]       99.73     0.27     818
37        subclasificacion  [<class 'str'>, <class 'float'>]       99.73     0.27     818
38        sub_tipo_recurso  [<class 'str'>, <class 'float'>]       99.89     0.11     348
39              fecha_data                   [<class 'str'>]      100.00     0.00       0
--------------------------------------------------------------------------------

Nombre de fichero: capitulo-iv-pozos.csv      encoding= UTF-8-SIG

               nombre_campo                        tipo_datos  no_nulos_%  nulos_%  nulos
0                     sigla                   [<class 'str'>]      100.00     0.00      0
1                    idpozo                   [<class 'int'>]      100.00     0.00      0
2                      area                   [<class 'str'>]      100.00     0.00      0
3                  cod_area                   [<class 'str'>]      100.00     0.00      0
4                   empresa  [<class 'str'>, <class 'float'>]       98.96     1.04    874
5                yacimiento                   [<class 'str'>]      100.00     0.00      0
6            cod_yacimiento                   [<class 'str'>]      100.00     0.00      0
7                 formacion  [<class 'str'>, <class 'float'>]       96.65     3.35   2815
8                    cuenca                   [<class 'str'>]      100.00     0.00      0
9                 provincia                   [<class 'str'>]      100.00     0.00      0
10                     cota                 [<class 'float'>]      100.00     0.00      0
11              profundidad                 [<class 'float'>]      100.00     0.00      0
12            clasificacion                   [<class 'str'>]      100.00     0.00      0
13         subclasificacion                   [<class 'str'>]      100.00     0.00      0
14             tipo_recurso                   [<class 'str'>]      100.00     0.00      0
15         sub_tipo_recurso                   [<class 'str'>]      100.00     0.00      0
16                  gasplus                   [<class 'str'>]      100.00     0.00      0
17                 tipopozo                   [<class 'str'>]      100.00     0.00      0
18           tipoextraccion                   [<class 'str'>]      100.00     0.00      0
19               tipoestado                   [<class 'str'>]      100.00     0.00      0
20  adjiv_fecha_inicio_perf  [<class 'str'>, <class 'float'>]       59.35    40.65  34141
21     adjiv_fecha_fin_perf  [<class 'str'>, <class 'float'>]       59.18    40.82  34286
22  adjiv_fecha_inicio_term  [<class 'str'>, <class 'float'>]       56.44    43.56  36583
23     adjiv_fecha_fin_term  [<class 'str'>, <class 'float'>]       56.44    43.56  36582
24                  geojson                   [<class 'str'>]      100.00     0.00      0
25                     geom                   [<class 'str'>]      100.00     0.00      0
--------------------------------------------------------------------------------

Nombre de fichero: produccin-de-pozos-de-gas-y-petrleo-2020.csv      encoding= UTF-8-SIG

              nombre_campo                        tipo_datos  no_nulos_%  nulos_%   nulos
0                idempresa                   [<class 'str'>]      100.00     0.00       0
1                     anio                   [<class 'int'>]      100.00     0.00       0
2                      mes                   [<class 'int'>]      100.00     0.00       0
3                   idpozo                   [<class 'int'>]      100.00     0.00       0
4                 prod_pet                 [<class 'float'>]      100.00     0.00       0
5                 prod_gas                 [<class 'float'>]      100.00     0.00       0
6                prod_agua                 [<class 'float'>]      100.00     0.00       0
7                 iny_agua                 [<class 'float'>]      100.00     0.00       0
8                  iny_gas                 [<class 'float'>]      100.00     0.00       0
9                  iny_co2                 [<class 'float'>]      100.00     0.00       0
10                iny_otro                 [<class 'float'>]      100.00     0.00       0
11                     tef                 [<class 'float'>]      100.00     0.00       0
12               vida_util                 [<class 'float'>]        4.51    95.49  910634
13          tipoextraccion  [<class 'str'>, <class 'float'>]      100.00     0.00      36
14              tipoestado  [<class 'str'>, <class 'float'>]      100.00     0.00      36
15                tipopozo  [<class 'str'>, <class 'float'>]      100.00     0.00      36
16           observaciones  [<class 'float'>, <class 'str'>]        7.78    92.22  879508
17            fechaingreso                   [<class 'str'>]      100.00     0.00       0
18             rectificado                   [<class 'str'>]      100.00     0.00       0
19              habilitado                   [<class 'str'>]      100.00     0.00       0
20               idusuario                   [<class 'int'>]      100.00     0.00       0
21                 empresa                   [<class 'str'>]      100.00     0.00       0
22                   sigla                   [<class 'str'>]      100.00     0.00       0
23                formprod  [<class 'str'>, <class 'float'>]       96.63     3.37   32160
24             profundidad                 [<class 'float'>]      100.00     0.00       0
25               formacion  [<class 'str'>, <class 'float'>]       96.49     3.51   33515
26  idareapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
27    areapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
28        idareayacimiento                   [<class 'str'>]      100.00     0.00       0
29          areayacimiento                   [<class 'str'>]      100.00     0.00       0
30                  cuenca  [<class 'str'>, <class 'float'>]      100.00     0.00      36
31               provincia                   [<class 'str'>]      100.00     0.00       0
32         tipo_de_recurso                   [<class 'str'>]      100.00     0.00       0
33                proyecto                   [<class 'str'>]      100.00     0.00       0
34           clasificacion  [<class 'str'>, <class 'float'>]       77.72    22.28  212456
35        subclasificacion  [<class 'str'>, <class 'float'>]       77.72    22.28  212456
36        sub_tipo_recurso  [<class 'float'>, <class 'str'>]        3.32    96.68  921968
37              fecha_data                   [<class 'str'>]      100.00     0.00       0
--------------------------------------------------------------------------------

Nombre de fichero: produccin-de-pozos-de-gas-y-petrleo-2021.csv      encoding= UTF-8-SIG

              nombre_campo                        tipo_datos  no_nulos_%  nulos_%   nulos
0                idempresa                   [<class 'str'>]      100.00     0.00       0
1                     anio                   [<class 'int'>]      100.00     0.00       0
2                      mes                   [<class 'int'>]      100.00     0.00       0
3                   idpozo                   [<class 'int'>]      100.00     0.00       0
4                 prod_pet                 [<class 'float'>]      100.00     0.00       0
5                 prod_gas                 [<class 'float'>]      100.00     0.00       0
6                prod_agua                 [<class 'float'>]      100.00     0.00       0
7                 iny_agua                 [<class 'float'>]      100.00     0.00       0
8                  iny_gas                 [<class 'float'>]      100.00     0.00       0
9                  iny_co2                 [<class 'float'>]      100.00     0.00       0
10                iny_otro                 [<class 'float'>]      100.00     0.00       0
11                     tef                 [<class 'float'>]      100.00     0.00       0
12               vida_util                 [<class 'float'>]        4.13    95.87  921768
13          tipoextraccion  [<class 'str'>, <class 'float'>]      100.00     0.00      38
14              tipoestado  [<class 'str'>, <class 'float'>]      100.00     0.00      38
15                tipopozo  [<class 'str'>, <class 'float'>]      100.00     0.00      38
16           observaciones  [<class 'str'>, <class 'float'>]        6.93    93.07  894839
17            fechaingreso                   [<class 'str'>]      100.00     0.00       0
18             rectificado                   [<class 'str'>]      100.00     0.00       0
19              habilitado                   [<class 'str'>]      100.00     0.00       0
20               idusuario                   [<class 'int'>]      100.00     0.00       0
21                 empresa                   [<class 'str'>]      100.00     0.00       0
22                   sigla                   [<class 'str'>]      100.00     0.00       0
23                formprod  [<class 'str'>, <class 'float'>]       96.66     3.34   32160
24             profundidad                 [<class 'float'>]      100.00     0.00       0
25               formacion  [<class 'str'>, <class 'float'>]       96.51     3.49   33516
26  idareapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
27    areapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
28        idareayacimiento                   [<class 'str'>]      100.00     0.00       0
29          areayacimiento                   [<class 'str'>]      100.00     0.00       0
30                  cuenca  [<class 'str'>, <class 'float'>]      100.00     0.00      36
31               provincia                   [<class 'str'>]      100.00     0.00       0
32         tipo_de_recurso                   [<class 'str'>]      100.00     0.00       0
33                proyecto                   [<class 'str'>]      100.00     0.00       0
34           clasificacion  [<class 'str'>, <class 'float'>]       77.89    22.11  212558
35        subclasificacion  [<class 'str'>, <class 'float'>]       77.89    22.11  212558
36        sub_tipo_recurso  [<class 'float'>, <class 'str'>]        3.58    96.42  926988
37              fecha_data                   [<class 'str'>]      100.00     0.00       0
--------------------------------------------------------------------------------

Nombre de fichero: produccin-de-pozos-de-gas-y-petrleo-2022.csv      encoding= UTF-8-SIG

              nombre_campo                        tipo_datos  no_nulos_%  nulos_%   nulos
0                idempresa                   [<class 'str'>]      100.00     0.00       0
1                     anio                   [<class 'int'>]      100.00     0.00       0
2                      mes                   [<class 'int'>]      100.00     0.00       0
3                   idpozo                   [<class 'int'>]      100.00     0.00       0
4                 prod_pet                 [<class 'float'>]      100.00     0.00       0
5                 prod_gas                 [<class 'float'>]      100.00     0.00       0
6                prod_agua                 [<class 'float'>]      100.00     0.00       0
7                 iny_agua                 [<class 'float'>]      100.00     0.00       0
8                  iny_gas                 [<class 'float'>]      100.00     0.00       0
9                  iny_co2                 [<class 'float'>]      100.00     0.00       0
10                iny_otro                 [<class 'float'>]      100.00     0.00       0
11                     tef                 [<class 'float'>]      100.00     0.00       0
12               vida_util                 [<class 'float'>]        2.87    97.13  944440
13          tipoextraccion  [<class 'str'>, <class 'float'>]       99.99     0.01     136
14              tipoestado  [<class 'str'>, <class 'float'>]       99.99     0.01     136
15                tipopozo  [<class 'str'>, <class 'float'>]       99.99     0.01     136
16           observaciones  [<class 'str'>, <class 'float'>]        6.37    93.63  910409
17            fechaingreso                   [<class 'str'>]      100.00     0.00       0
18             rectificado                   [<class 'str'>]      100.00     0.00       0
19              habilitado                   [<class 'str'>]      100.00     0.00       0
20               idusuario                   [<class 'int'>]      100.00     0.00       0
21                 empresa                   [<class 'str'>]      100.00     0.00       0
22                   sigla                   [<class 'str'>]      100.00     0.00       0
23                formprod  [<class 'str'>, <class 'float'>]       96.69     3.31   32160
24             profundidad                 [<class 'float'>]      100.00     0.00       0
25               formacion  [<class 'str'>, <class 'float'>]       96.55     3.45   33516
26  idareapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
27    areapermisoconcesion                   [<class 'str'>]      100.00     0.00       0
28        idareayacimiento                   [<class 'str'>]      100.00     0.00       0
29          areayacimiento                   [<class 'str'>]      100.00     0.00       0
30                  cuenca  [<class 'str'>, <class 'float'>]      100.00     0.00      36
31               provincia                   [<class 'str'>]      100.00     0.00       0
32         tipo_de_recurso                   [<class 'str'>]      100.00     0.00       0
33                proyecto                   [<class 'str'>]      100.00     0.00       0
34           clasificacion  [<class 'str'>, <class 'float'>]       78.13    21.87  212646
35        subclasificacion  [<class 'str'>, <class 'float'>]       78.13    21.87  212646
36        sub_tipo_recurso  [<class 'float'>, <class 'str'>]        4.00    96.00  933479
37              fecha_data                   [<class 'str'>]      100.00     0.00       0
--------------------------------------------------------------------------------

Nombre de fichero: produccin-de-pozos-de-gas-y-petrleo-2023.csv      encoding= UTF-8-SIG

              nombre_campo                        tipo_datos  no_nulos_%  nulos_%   nulos
0                idempresa                   [<class 'str'>]      100.00     0.00       0
1                     anio                   [<class 'int'>]      100.00     0.00       0
2                      mes                   [<class 'int'>]      100.00     0.00       0
3                   idpozo                   [<class 'int'>]      100.00     0.00       0
4                 prod_pet                 [<class 'float'>]      100.00     0.00       0
5                 prod_gas                 [<class 'float'>]      100.00     0.00       0
6                prod_agua                 [<class 'float'>]      100.00     0.00       0
7                 iny_agua                 [<class 'float'>]      100.00     0.00       0
8                  iny_gas                 [<class 'float'>]      100.00     0.00       0
9                  iny_co2                 [<class 'float'>]      100.00     0.00       0
10                iny_otro                 [<class 'float'>]      100.00     0.00       0
11                     tef                 [<class 'float'>]      100.00     0.00       0
12               vida_util                 [<class 'float'>]        2.53    97.47  950318
13          tipoextraccion  [<class 'str'>, <class 'float'>]      100.00     0.00      41
14              tipoestado  [<class 'str'>, <class 'float'>]      100.00     0.00      41
15                tipopozo  [<class 'str'>, <class 'float'>]      100.00     0.00      41
16           observaciones  [<class 'str'>, <class 'float'>]        6.93    93.07  907381
17            fechaingreso                   [<class 'str'>]      100.00     0.00       0
18             rectificado                   [<class 'str'>]      100.00     0.00       0
19              habilitado                   [<class 'str'>]      100.00     0.00       0
20               idusuario                   [<class 'int'>]      100.00     0.00       0
21                 empresa                   [<class 'str'>]      100.00     0.00       0
22                   sigla                   [<class 'str'>]      100.00     0.00       0
23                formprod  [<class 'str'>, <class 'float'>]       96.70     3.30   32160
24             profundidad                 [<class 'float'>]      100.00     0.00       0